### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by Ben80850** [Jhangju/offode#1]
Hello
I would like to use your tool but I got this error and I have trouble understanding how to solve it. Is it possible to have an explanation on how to solve it or a hint? Thank you in advance.
![Offode](https://user-images.githubusercontent.com/83580959/167887196-e57222a5-0682-4fcb-8138-4fe514116265.PNG)

**Comment by Jhangju** [comment]
Don't use headless browser.
And try it on windows because I did not test it on server.
